tracker_bot/track/urls.py
from django.contrib import admin
from django.urls import path
from .views import home,LinkDeleteView,updating

urlpatterns=[
    path('admin/',admin.site.urls),
    path('',home,name='home'),
    path('delete/<pk>/',LinkDeleteView.as_view(), name='delete'),
    #path('change/<int:amaze_id>/',changed,name="change"),
    path('update/',updating,name="updates")
]


tracker_bot/tracker_bot/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from track.views import home,LinkDeleteView,updating

urlpatterns = [
    path('admin/', admin.site.urls),
    path('track/',include(('track.urls','track'),namespace="track"))

]

tracker_bot/track/models.py
from django.db import models
from .tracking import checker

# Create your models here.

class amaze(models.Model):
    name=models.CharField(max_length=220,blank=True)
    url=models.URLField()
    curr_val=models.FloatField(blank=True)
    exp_val=models.FloatField(default=0)
    differ=models.FloatField(default=0)
    modified=models.DateField(auto_now=True)
    created=models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering=('differ','-created')
    
    def save(self, *args, **kwargs):

        name,price=checker(self.url)
        old_price=self.exp_val
        if self.curr_val:
            if price!=old_price:
               old_price=self.exp_val
               diff=price-old_price
               self.differ=round(diff,2)
            else:
                self.differ=0
            
            
        self.name=name
        self.curr_val=price
        super().save(*args, **kwargs)



tracker_bot/track/forms.py
from django import forms
from .models import amaze

class amazeform(forms.ModelForm):
    class Meta:
        model = amaze
        fields = ("url","exp_val",)


tracker_bot/track/views.py
from django.shortcuts import get_object_or_404, render,redirect
from .forms import amazeform
from .models import amaze
from django.urls import reverse_lazy
from django.views.generic import DeleteView,UpdateView
import requests
# Create your views here.

def home(request):
    no_discounts=0
    error=None 
    form=amazeform(request.POST or None)

    if request.method =='POST':
        try:
            if form.is_valid():
                form.save()
                form.save()
              
        except:
            error="Sorry! Something is wrong"
        
    form=amazeform()
    lists=amaze.objects.all()
    item_no=lists.count()
    count_disc=0
    if item_no>0:
        disc_liss=[]
        for item in lists:
            if item.exp_val>item.curr_val:
                disc_liss.append(item)
            count_disc=len(disc_liss)


    context={"lists":lists,
    "item_no":item_no,
    "count_disc":count_disc,
    "form":form,
    "error":error
    }

    return render(request,'track/main.html',context)


class LinkDeleteView(DeleteView):
    model=amaze
    template_name="track/delete.html"
    success_url=reverse_lazy('track:home')
    
def updating(request):
    qs=amaze.objects.all()
    for link in qs:
        link.save()
    return redirect("track:home")

'''def changed(request,amaze_id):
    chan=request.POST.get('c', False)
    obj=get_object_or_404(amaze,id=amaze_id)
    obj.old_val=chan
    obj.save()
    return render(request,'track/main.html',context)


class changed(UpdateView):
    model=amaze
    fields=['old_val']
    template_name="track/change.html"
    success_url=reverse_lazy('track:home')'''

        


    
    








tracker_bot/track/templates/track/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Amazon price tracker</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}


        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

tracker_bot/track/templates/track/change.html
{%extends "track/base.html" %}
{%block content%}
<form method="POST" action="{%url 'track:home'%}">
    {%csrf_token %}
    <p>Change the price of the item: <strong>{{object.name}}</strong></p>
    <label><strong>Price: </strong></label>
    <input type="number" name="c" step="any" />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content%}

tracker_bot/track/templates/track/delete.html
{%extends "track/base.html" %}
{%block content%}
<form method="POST" action="">
    {%csrf_token %}
    <p>Are you sure you want to delete the item: <strong>{{object.name}}</strong></p>
    <button type="submit" class="btn btn-primary"> yes</button>
</form>
{% endblock content%}



tracker_bot/track/templates/track/main.html
{% extends "track/base.html" %}
{% load crispy_forms_tags %}
{% block content%}
{% load coloring %}


  <!-- Modal -->
  <div class="modal fade" id="additemModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add an item for tracking</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="" method="POST" autocomplete="off">
              {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  
<div class="row">
    <div class="col">
        <button class="btn btn-primary" data-toggle="modal" data-target="#additemModal">Add</button>
        <a href="{%url 'track:updates'%}">
        <button class="btn btn-info">Update</button>
        </a>
    </div>
        <div class="col" style="text-align:right">
            <div><strong>Total no of items tracked: {{item_no}}</strong></div>
            <div><strong>Discounted items: {{count_disc}} </strong></div>
        </div>
    </div>
    {% if lists %}
      {% for item in lists %}
        <div class="card mt-3">
            <div class="card-header">
                <h5>{{item.name}}</h5>
                <a href={%url 'track:delete' item.id %}><button class="btn btn-danger">Delete</button></a>
            </div>
          </div>
        <div class="card-body">
            <div class="blockquote">
            <div>Current price: {{item.curr_val}}</div>
            <div>Expected deal: {{item.exp_val}}</div>
            <div>Difference: {{item.differ|coloring}}</div>
            <div>Link:<a href="{{item.url}}">{{item.url}}</a></div>
            </div>
        </div>


    {%endfor %}
    {% else %}
    <h3> No items are tracked currently </h3>
    {% endif %}
{% endblock %}